### ISSUE TITLE
RPM package conflicts

### ISSUE THREAD

**Issue by peterverraedt** [irods/irods_rule_engine_plugin_audit_amqp#104]
Installing the build rpm of this plugin results in package conflicts on centos 7:

Transaction check error:
  file /var/lib/irods/scripts conflicts between attempted installs of irods-rule-engine-plugin-audit-amqp-4.3.0.0-1.x86_64 and irods-server-4.3.0-1.x86_64
  file /var/lib/irods/scripts/irods conflicts between attempted installs of irods-rule-engine-plugin-audit-amqp-4.3.0.0-1.x86_64 and irods-server-4.3.0-1.x86_64
  file /var/lib/irods/scripts/irods/test conflicts between attempted installs of irods-rule-engine-plugin-audit-amqp-4.3.0.0-1.x86_64 and irods-server-4.3.0-1.x86_64

**Comment by alanking** [comment]
Seems like we missed this one in the run up to 4.3.0.0 for a change which was necessary in several of our plugin repositories for RPMs:

https://github.com/irods/irods_microservice_plugins_curl/pull/49
https://github.com/irods/irods_capability_storage_tiering/pull/205
https://github.com/irods/irods_rule_engine_plugin_logical_quotas/pull/73

Thanks for the report
