### ISSUE TITLE
Cannot build against 4.3.0

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_rule_engine_plugin_audit_amqp#116]
820433ed2ff52993f69c055b0d6bbd0d8302986e needs to be reverted temporarily, as long as we need to continue to build against 4.3.0

**Comment by korydraughn** [comment]
Hmm. That doesn't sound like a bad idea, but it's possible there may never be a difference between the main branch and the 43s branch.

**Comment by alanking** [comment]
Well, to be clear, I'm proposing a 4-3-0-stable (emphasis on the 0; not 4-3-stable). We already have a difference documented here in the "temporary" nature of the revert. The plugin builds against 4.3.1/main as-is, I understand it, so this branch would just exist for the 4.3.0.x release. Without that branch, we would need to revert the revert after the 4.3.0.0 tag is pushed and if for whatever reason we need a 4.3.0.1 we would need to do it again. But that seems unlikely

**Comment by korydraughn** [comment]
I missed the 4-3-0-stable.

I see now. A new branch is fine.

**Comment by alanking** [comment]
Since 4.3.0.1 will be released from the 4-3-0-stable branch, we don't need to revert the revert anymore. The changes in #117/#118 fixed the build against iRODS 4.3.0. Closing.
