### ISSUE TITLE
iCommands return `CLIENT_NEGOTIATION_ERROR` when `".*"` is used as the regular expression to match

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_rule_engine_plugin_audit_amqp#124]
This was observed while manually testing the audit plugin (510f53e) for what will most likely be iRODS 4.3.1 ([irods/irods/tree/97eb33f](https://github.com/irods/irods/tree/97eb33f130349db5e01a4b85e89dd1da81460345)). The OS was Ubuntu 20.04.

To reproduce, stand up a rabbitmq:3-management docker container (available via docker hub), make the audit plugin's regex `".*"`, and then execute `ils`.

The weird part is the issues go away if `"pep.*"` or any regex other than `".*"` is used.

**Comment by SwooshyCueb** [comment]
I'm curious, have you tried `.+`?

**Comment by korydraughn** [comment]
I haven't. Will give that a try tomorrow.

**Comment by korydraughn** [comment]
It resulted in the same error.

**Comment by trel** [comment]
do any messages make it to the broker?   wondering what else it is matching that is clogging up the server...

**Comment by korydraughn** [comment]
Yes. I originally thought it could be a data type that the audit plugin didn't understand, but the serialization logic has that case covered.

**Comment by trel** [comment]
and all the messages that make it to the broker start with `pep_`?

**Comment by korydraughn** [comment]
I didn't check that. There's a lot of messages in there and I never figured out how to access them via the command line. The GUI is very limited. I didn't see a way to easily check the contents of the messages because they're all base64 encoded.

The messages I did decode looked fine on a structural level.

**Comment by trel** [comment]
Okay, we'll investigate more after release.

**Comment by korydraughn** [comment]
I have not been able to reproduce this using the 4.3.1.0 or 4.3.2.0 plugins. All reported PEPs are being captured as expected. The icommands are not experiencing errors.

Everything is working as expected. Closing.
