### ISSUE TITLE
Install of 'unittest-xml-reporting==1.14.0' in test hook breaks tests

### ISSUE THREAD

**Issue by FifthPotato** [irods/irods_rule_engine_plugin_audit_amqp#156]
- [x] main
- [x] 4-3-stable

---

Testing breaks on ubuntu24 due to the install of unittest-xml-reporting==1.14.0 in the test hook.
The fix is to delete https://github.com/irods/irods_rule_engine_plugin_audit_amqp/blob/8d7354f4a2d7743ae8a76c1646e9ba905c902f88/irods_consortium_continuous_integration_test_hook.py#L113

**Comment by trel** [comment]
how/why does it break?   can you share the error you see?

**Comment by korydraughn** [comment]
It's the same issue as this.

https://github.com/irods/irods_capability_storage_tiering/issues/275

**Comment by trel** [comment]
ah, so old that it's in conflict.   got it.
