### ISSUE TITLE
Bump externals dependencies to match irods/irods 4-2-stable

### ISSUE THREAD

**Issue by alanking** [irods/irods_rule_engine_plugin_audit_amqp#30]
Revert 23e7390ad0522ae3b0bbe8fd0b121d48aa593452 before release of 4.2.8.0.

**Comment by trel** [comment]
is this complete? @jassigill2000 @alanking

**Comment by alanking** [comment]
https://github.com/irods/irods_rule_engine_plugin_audit_amqp/commit/0defa159032505b7ce257e30b9721bfc297bd1ea claims to revert the SHA mentioned in the original message for 4-2-stable.

https://github.com/irods/irods_rule_engine_plugin_audit_amqp/commit/3a69ae1e135a4738163eda7570b5c18d8e3a6f5f is the version for master, although the commit message is incorrect (the SHA is different in master).

I believe this is finished.

**Comment by trel** [comment]
good good - closing.
