### ISSUE TITLE
replace use of jansson library with json library

### ISSUE THREAD

**Issue by trel** [irods/irods_rule_engine_plugin_audit_amqp#42]
- [ ] master
- [ ] 4-2-stable

**Comment by d-w-moore** [comment]
I'll work on this

**Comment by SwooshyCueb** [comment]
@alanking can you tick the box for main on this one?

**Comment by alanking** [comment]
Done.

I was wondering about the backport to 4-2-stable. At this point, I wonder if this change might be out of scope since we are trying to close the curtain on 4.2.x with 4.2.12? Thoughts, @korydraughn?

**Comment by trel** [comment]
I think I agree... the rest of 4.2.x will still have jansson, removing it from this plugin is 'just extra work'?

**Comment by korydraughn** [comment]
I agree. If the work isn't trivial or doesn't fix a severe bug, we should ignore it for 4-2-stable.

**Comment by korydraughn** [comment]
@trel Let's remove the check boxes from this issue since we all agree this is 4.3 only.

**Comment by trel** [comment]
done
