### ISSUE TITLE
plugin produces invalid json

### ISSUE THREAD

**Issue by bh9** [irods/irods_rule_engine_plugin_audit_amqp#57]
ubuntu 18.04
irods 4.2.10
rabbitmq 3.9.1-1
logstash 1:7.13.4-1 
elasticsearch 7.3

The audit plugin seems to produce invalid JSON, but I'm not sure if the issue is the apparent extra encoding or the extra characters on the front
Example log message from logstash:
```
[2021-08-04T00:00:36,097][WARN ][logstash.codecs.json     ][main][460fd1cab4fb1577f05006c1a347cf89fd9e31cecd312044974fd5bd5c041e83] Received an event that has a different character encoding than you configured. {:text=>"\\u0000Sw\\xA1\\x80__BEGIN_JSON__{\\\"time_stamp\\\": \\\"1628035236041\\\", \\\"hostname\\\": \\\"bh9-irods-build-test\\\", \\\"pid\\\": \\\"18553\\\", \\\"action\\\": \\\"START\\\"}__END_JSON__", :expected_charset=>"UTF-8"}
```
Example document in elasticsearch:
```
{
  "_index": "irods-audit-plugin-test",
  "_type": "_doc",
  "_id": "Z0CyEXsBRx9u572Za_8m",
  "_version": 1,
  "_score": null,
  "_source": {
    "tags": [
      "_jsonparsefailure"
    ],
    "@version": "1",
    "@timestamp": "2021-08-04T15:05:10.591Z",
    "message": "\\u0000Sw\\xA1~__BEGIN_JSON__{\\\"time_stamp\\\": \\\"1628089510585\\\", \\\"hostname\\\": \\\"bh9-irods-build-test\\\", \\\"pid\\\": \\\"31387\\\", \\\"action\\\": \\\"END\\\"}__END_JSON__"
  },
  "fields": {
    "@timestamp": [
      "2021-08-04T15:05:10.591Z"
    ]
  },
  "sort": [
    1628089510591
  ]
}
```

**Comment by d-w-moore** [comment]
@bh9  Possible workaround for now... With a total of 3 gsub operations (one each for stripping BEGIN_JSON and END_JSON tags, and one to remove the backslashes before quotes, I think logstash could be configured to handle this roguish formatting. Cutting-and-pasting in from the logstash excerpt you gave above, into  an irb (Ruby) prompt:

```
> Input = "\\u0000Sw\\xA1\\x80__BEGIN_JSON__{\\\"time_stamp\\\": \\\"1628035236041\\\", \\\"hostname\\\": \\\"bh9-irods-build-test\\\", \\\"pid\\\": \\\"18553\\\", \\\"action\\\": \\\"START\\\"}__END_JSON__<potentially_other_garbage_here>"

> Stripped_input = input.gsub(/.*__BEGIN_JSON__/,"").gsub(/__END_JSON__.*/,"")

> puts( De_Escaped = Stripped_input.gsub('\\"','"'))
{"time_stamp": "1628035236041", "hostname": "bh9-irods-build-test", "pid": "18553", "action": "START"}
=> nil

> require 'json'  ## _ _ _ _ to prove we can parse it now: _ _ _ _

> Json_Deserialized = JSON.parse(  De_Escaped  )
=> {"time_stamp"=>"1628035236041", "hostname"=>"bh9-irods-build-test", "pid"=>"18553", "action"=>"START"}

```

**Comment by bh9** [comment]
That almost got it, but I then had to also reattempt the json parsing, since it must have already failed by then. The functional logstash filter is 
```
filter {
  mutate {
    gsub => [ "message", ".*__BEGIN_JSON__", "" ]
    gsub => [ "message", "__END_JSON__.*", "" ]
    gsub => [ "message", '\\"', '"' ]
  }
  json {
    source => "message"
  }
}
```

**Comment by d-w-moore** [comment]
Excellent,  I must learn some logstash soon.  The Ruby syntax can make this stuff a little bit tricky...

**Comment by d-w-moore** [comment]
@bh9 Also: a possible alternative to using the `Stripped_input.gsub('\\"','"'))` substitution might be: ` eval( %q!"! + Stripped_input +  %q!"! )` and it might handle more cases, though it makes some assumptions, ie. not all generated JSON has ruby-isms in it :/ .  So, grain of NaCl....

**Comment by SwooshyCueb** [comment]
Logstash does not speak AMQP 1.0. Now that our elk docker image has swapped Logstash for a broker fluent in AMQP 1.0, this issue can be closed.
