### ISSUE TITLE
Incomplete package dependencies

### ISSUE THREAD

**Issue by epl2t1n** [irods/irods_rule_engine_plugin_audit_amqp#6]
The .deb package that is build according to the build instructions is missing a dependency on one (or more) of the externals: irods-externals-qpid-with-proton0.34-0.

The CentOS7 generated rpm's also do not install correctly they clash with the other irods installed external packages (installed on an irods-server).

**Comment by trel** [comment]
@epl2t1n This should fix the package dependencies.

I'm not sure about the CentOS7 clashing.  We have tests running with CentOS7 in CI.  If you have a way to reproduce a clash, please open another issue.
