### ISSUE TITLE
The audit plugin only works with particular versions of ActiveMQ.

### ISSUE THREAD

**Issue by epl2t1n** [irods/irods_rule_engine_plugin_audit_amqp#7]
Deploying the audit plugin we have been running into several issues, the main issue is that the plugin does not seem to work with the latest versions of ActiveMQ;

ActiveMQ version 5.13.x works fine, but the latest versions of ActiveMQ 5.14.x do not work.

Also with RabbitMQ (incl. AMQP 1.0 plugin) we haven't been able to get this to function. Should this work at all? since it is not included in the audit-plugin example.

**Comment by trel** [comment]
We have confirmed this behavior.  ActiveMQ 5.14 began requiring the SASL layer information to be populated.

We found this discussion leading us to the solution:
  https://stackoverflow.com/questions/43873400/unable-to-connect-to-apache-activemq-with-node-js

We have duplicated and satisfied the newly required authentication by simply adding 'ANONYMOUS@' in the iRODS configuration being sent to the proton library.

We are working to confirm this fix works with RabbitMQ as well.  We plan to have all three of these in CI before release.

Thanks for the bug report.

**Comment by trel** [comment]
At this time, we plan to release 1.0 with tests that pass against ActiveMQ 5.13.x and ActiveMQ 5.14.x.

ActiveMQ 5.15.x has passed on the bench - but requires a newer Java than we have in CI

RabbitMQ has passed on the bench - but is proving tricky to configure in CI.  RabbitMQ knowledge willingly accepted from the community.

**Comment by trel** [comment]
@epl2t1n I hope this satisfies your use cases.  Please open another issue if we're still coming up short.  Thank you.
