### ISSUE TITLE
Investigate `test_resource_types.Test_Resource_Unixfilesystem` in test hook

### ISSUE THREAD

**Issue by alanking** [irods/irods_rule_engine_plugin_audit_amqp#81]
It was added in #19 because of irods/irods#3879. Is there a better way to do this?

**Comment by trel** [comment]
a single test that covers all the serializations we use/need?

**Comment by alanking** [comment]
Assigning self in order to provide stop-gap solution. Real solution - test covering all of the known serializations - can come later.
