### ISSUE TITLE
Build fails on Centos 7 with latest qpid-proton external (main)

### ISSUE THREAD

**Issue by alanking** [irods/irods_rule_engine_plugin_audit_amqp#84]
Again, this is only applicable to Centos 7. When I build the main branch (squeaky clean), I see the following:
```
stdout: [ 50%] Building CXX object CMakeFiles/irods_rule_engine_plugin-audit_amqp.dir/libirods_rule_engine_plugin-audit_amqp.cpp.o

stderr: make[2]: *** No rule to make target `/opt/irods-externals/qpid-proton0.36.0-0/lib/libqpid-proton.so', needed by `libirods_rule_engine_plugin-audit_amqp.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```
I tried downloading the qpid-proton external (`yum install irods-externals-qpid-proton0.36.0-0`) and see the following:
```bash
$ ls /opt/irods-externals/qpid-proton0.36.0-0/ -l
total 4
drwxr-xr-x 3 root root 4096 Apr  6 13:01 include
```

As you can see, the `lib` subdirectory is missing. For comparison, I installed the same external package on Ubuntu 18.04 and see the following:
```bash
$ ls /opt/irods-externals/qpid-proton0.36.0-0/ -l
total 8
drwxr-xr-x 3 root root 4096 Apr  6 13:07 include
drwxr-xr-x 4 root root 4096 Apr  6 13:07 lib
```

Should I be using a different version of `qpid-proton`, or is the RPM build for this external broken?

**Comment by korydraughn** [comment]
I'll also look into wrapping up my PR. Maybe it has changes that fix this.

**Comment by alanking** [comment]
```json
    "qpid-proton": {
        "commitish": "0.36.0",
        "version_string": "0.36.0",
        "license": "Apache License 2.0",
        "consortium_build_number": "0",
        "externals_root": "opt/irods-externals",
        "build_steps": [
            "mkdir -p build",
            "cd build; TEMPLATE_CMAKE_EXECUTABLE -DCMAKE_CXX_COMPILER=TEMPLATE_CLANGPP_EXECUTABLE -DCMAKE_C_COMPILER=TEMPLATE_CLANG_EXECUTABLE -DCMAKE_CXX_FLAGS='-nostdinc++ -ITEMPLATE_CLANG_CPP_HEADERS' -DCMAKE_SHARED_LINKER_FLAGS='-LTEMPLATE_CLANG_CPP_LIBRARIES -stdlib=libc++' -DCMAKE_EXE_LINKER_FLAGS='-LTEMPLATE_CLANG_CPP_LIBRARIES -stdlib=libc++' -DCMAKE_INSTALL_PREFIX=TEMPLATE_INSTALL_PREFIX -DBUILD_JAVA=OFF -DBUILD_RUBY=OFF -DBUILD_PYTHON=OFF -DSYSINSTALL_BINDINGS=OFF -DENABLE_LINKTIME_OPTIMIZATION=NO ..",
            "cd build; make -jTEMPLATE_JOBS; make install"
        ],
        "external_build_steps": [
            "ls -l TEMPLATE_INSTALL_PREFIX/../* ; cp -rf TEMPLATE_INSTALL_PREFIX/../* ../../ ; ls -l ../../"
        ],
        "fpm_directories": ["include", "lib"]
    },
```
(see: https://github.com/irods/externals/blob/876b2a0360a2c4d69134c0329b74c12c7bd300cc/versions.json#L350-L365)

The version number matches. I'm building the external locally now for inspection

**Comment by trel** [comment]
it may be making a lib64

**Comment by alanking** [comment]
It does not create anything, at least not in `/opt/irods-externals/qpid-proton0.36.0-0`. I pasted the full output of `ls -l` above. Perhaps they appear elsewhere?

**Comment by alanking** [comment]
This did not produce the desired result, but now I have build artifacts to look at:
```bash
/path/to/externals$ ls -l qpid-proton0.36.0-0
total 12
drwxr-xr-x 3 root root 4096 Apr  6 23:03 include
drwxr-xr-x 4 root root 4096 Apr  6 23:03 lib64
drwxr-xr-x 3 root root 4096 Apr  6 23:03 share
```
So, `lib64` is in fact being produced, but not making it into the package. I added "lib64" to the list of "fpm_directories" in versions.json and it packaged up the `lib64` directory.

I'm still getting the same build error, but this is progress. I'll keep toying with it

**Comment by alanking** [comment]
Oh, duh
https://github.com/irods/irods_rule_engine_plugin_audit_amqp/blob/f751b1934bce191947c606037d80897e63a1fb54/CMakeLists.txt#L67
There it is

**Comment by trel** [comment]
well, if we can get the build to produce `lib` only, then we're good.

**Comment by alanking** [comment]
Looking into the options a bit more and found this...

https://github.com/apache/qpid-proton/blob/6bded7019cc31fd699b1d53d378a4ec76bcdb689/CMakeLists.txt#L253-L269

So I tried hard-coding `LIB_SUFFIX` to an empty string, and that did the trick.

**Comment by alanking** [comment]
This problem doesn't exist on 4-2-stable as we only care about `qpid-with-proton` in that branch, so I think this can be closed.
